import React from "react";

export default function About() {
    return (
        <>
            <div> 
                <h2>
                    About Me
                </h2>
                <h4>My Name is Sam! ... and I am a JavaScript developer. </h4>
                <p>I used to work in the Solar industry and at the begining of 2023 I decided to change my career path and become a developer. So I signed up and completed <strong>an intense bootcamp program</strong> offered at the University of Toronto (UofT) [add link] by 2U [add link]. The program was very tough and the learning journey required a lot of time and patience. It was extremely rewarding and I completed it with great confidence and many new expertiese in my tool-belt.You can see the list of my programming languages, frameworks, devops, and tools under "My Resume" section [add link]. </p>
                <h3>My Story</h3>
                <p>I am a professional engineer with many years of experience in multidisciplinary industries. I have always been very curius about how everything works, and always took the more difficult path to challenge myself and to learn. I believe the best way of learning is by doing. That is the reason I took on the challenge of Bootcamp so that I can put myself through the tough rigure of learning by coding. And I have come a long way from the first days of writing only HTML code ;)</p>
                <h4>My Educations</h4>
                <p>When I was in highschool, I always knew that I want to study engineering. During senior year I took a coop course and I found a placement at an egineering firm where I learned to use AutoCAD and prepare engineering drawings for Electrical installations. They loved my work ethics and they hired me for the summer after I graduated. I always reached out to my manager and asked him advice on variety of topics. One of which was about choosing an engineering discipline. He told me that if you want to study any engineering, make sure to complement it with studying business along side it. Because even if you don't go into business, it will still make you understand how all other teams work in a corporate environment, and it will make you a more effective engineer. I took his advice and when I started my university education at McMaster University, I opt in for Engineering and Management programm. It was not an easy path, it took longer than my other friends who were in the straight engineering track. And I did not have any electives, as all my courses have been pre-defined by the programm. It was a mixture of technical engineering courses, and finance and accoungin, project management based on PMBOK, business strategy, marketing, and a whole lot of business administration courses. It was essencially a mini MBA while doing a full fledged Electrical and Computer Engineering. To this day, I am grateful for that advice and mentorship from my first engineering manager, Norm Fisher. I hope he is happy and healthy and doing well. Thank you Norm.</p>
                <h4>My Work Experiences</h4>
                <p>After graduating from McMaster, I looked at my education track and reflected on the years spend learning interesting and challenging subjects. I have always taken the more challenging paths as I find more rewards at the end. Upon detailed reflection, I realised that the technical and engineering subjects were much easier for me than the business skills where one must interact and manage expectations of other people. I felt that I was university graduate level in engineering subjects, but still elementary level in business. So I decided to go after the latter. Even though I had graduated from university with flying colors, my education was not yet finished. So I put myself outside of my comfort zone and worked as Project Coordinator with different companies. Where I learned how to navigate the human psyche and manage expectations of project owners, stakeholders, directors, bosses, and coworkers. I first started with major corporation on a multidisciplinary project where we had over 3000 engineers in house designing all fascets of a process fascility. It was a great learning opportunity for me at SNC Lavalin where I learned practical strategies for project planing, procurement, documentation, change management, public speaking, client relation management, and most importantly Project Control, where one must keep a keen eye on the budget and monitor and control spent resources while keeping the project on track against the initial project plan. My mentor was Guy Germaine, whose tough love and stern methods thought me how to keep calmn and move steady forward in the face of unpredictable project changes. That is were I learned the benefits of Agile aproach to project management. The greatest lesson I learned there was that "Change is an unavoidable part of any project or plan, and one must always be open to it and embrace it in order to move forward and come out successfull at the end". Merci Guy!</p>
                <p>After I learned all that was possible to me on that mega project with SNC Lavalin, it was time for me to move on to the next challenge, where I had to fullfill the technical requirement for obtaining my Professional Engineer license. I needed to work under direct supervision of another licensed Engineer in my discipline and carry out technical engineering work, in order to be eligible for my P.Eng. license. In considering my options, I decided to join a start up, where I could put to practice my newly refined project management skills while challenging myself in an unchartered teritory of a start up company, where through out a work-day I had to wear multiple hats (so to speak). I then answered an opportunity call at a solar startup, when solar was booming in Ontario, and joined Cameron Steinman and his young team of 4 at Endura Energy. There I learned the true meaning of the challenges that one must deal with on a daily basis in order to run a start up. I gained many insights about runing a company and managing work deliverables. I was truly outside of my comfort zone. It felt as if I had jumped in the deep end. So I put on my flippers and swam. We built many exciting projects all over Ontario, rooftop projects from commercial properties in the GTA to pig-farm barn roofs in farm courntry and even a few ground mount solar farms. It was an intense and rewarding opportunity to learn many greate deals about the regulatory systems, financing, construction, and even internal workings of a small business. Cameron was a gem, and a great mentor. I am always grateful for the opportunity that he gave me and for all the things I learned from him by osmosis. I believe I was still a child when I joined his team, and I had become a man by the time I left the company. Which was about the time my son was born, and I was ready to yet again take another challenge, and become a fultime dad and primary care giver for my new born while my wife finished her postgrad.</p>
                <p>I spent a few years in the solar industry and worked for a few companies at different capacity, and my responsibilities and accountabilities grew over time. By the time that the Ontario Solar Program (FIT) was coming to an end, I was leading the operations department at Grasshopper (the Solar City of Ontario) and was accountable for a multidisciplinary team of engineers and technical staff, where we built almost ALL of the residential solar rooftop projects in South West Ontario. Once the govenrment chose not to further extend the procurement mandate beyond 2018. I left the industry. By this time I have had accumulated a geate deal of experties and confidence in operations of a business. I felt that my education was coming to fruition, and now was the time for my capstone project.</p>
                <h4>My Personal Challenges</h4>
                <p>Through out my journey to this point, I had always worked for other companies, where I was responsible for a portion of the business. After my departure from the Solar Industry, I decided to challenge myself yet again, and put all of my accumulated experience to practice. I invested in a LASER scanning equipment with which I was able to scan a construction space in 3D and produce a CAD equivalent vector coordinate file to scale. I decided to pursuit this as my capstone callenge and see if I can make it into a business practice. It was ment only to be a test of my abilities, before I decide on the next chapter of my career. I attended many global conferences and spoke to many different industries to assess the demand for my services. I gattered the best entry point into this practice and connected with the manufactureres and fabricators who used CNC macnineries in the operation, for which they required detailed and exact scan of the space in order to make their products. Through persevierene and acquiered business development skills, I started networking and developing business relationships, and I started bringing in clients. I worked with fabricators of all materials, such as natural stone, glass, millwork (wood) and even steele. My work took me all over Canada and US, and even to the Carraebian island of Grand Cayman. I had graduated, and I was now running my full fledged B2B service practice for a variety of clients. I had created my own internal processes and standards. And all of my clients were happy with the work that I was producing. This project that started as a self challenge, has continued to produce for over 6 years.</p>
                <h4>Why I Became a Developer</h4>
                <p></p>


            </div>
        </>
    );
};